/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-03-24 08:38:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import magic.board.BoardBean;
import magic.board.BoardDBBean;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("magic.board.BoardBean");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("magic.board.BoardDBBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("\r\n");



	String pageNum =	request.getParameter("pageNum");

	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");

	int bid = Integer.parseInt(request.getParameter("b_id"));
	BoardDBBean db = BoardDBBean.getInstance();
// 	board 객체에 게시글의 정보가 저장되어 있음
//참으로 조회수 증가가 되어야하낟.
//조회수증가로 true 추가
// 	board 객체에 게시글의 정보가 저장되어 있음
//	BoardBean board = db.getBoard(bid);
	BoardBean board = db.getBoard(bid, true);//조회수 증가로 true 추가

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<center>\r\n");
      out.write("		<h1>글 내 용 보 기</h1>\r\n");
      out.write("		<table border=\"1\" width=\"600\" cellspacing=\"0\">\r\n");
      out.write("			<tr height=\"30\" align=\"center\">\r\n");
      out.write("				<td width=\"100\">글번호</td>\r\n");
      out.write("				<td width=\"200\">\r\n");
      out.write("					");
      out.print( bid );
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=\"100\">조회수</td>\r\n");
      out.write("				<td width=\"200\">\r\n");
      out.write("					");
      out.print( board.getB_hit() );
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr height=\"30\" align=\"center\">\r\n");
      out.write("				<td width=\"100\">작성자</td>\r\n");
      out.write("				<td width=\"200\">\r\n");
      out.write("					");
      out.print( board.getB_name() );
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=\"100\">작성일</td>\r\n");
      out.write("				<td width=\"200\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("					");
      out.print( sdf.format(board.getB_date()) );
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("<!-- 			출력도 다운로드도 할수 있게 한다. -->\r\n");
      out.write("			<tr height=\"30\" align=\"center\">\r\n");
      out.write("				<td width=\"100\">파&nbsp;&nbsp;일</td>\r\n");
      out.write("					<td colspan=\"3\">\r\n");
      out.write("						&nbsp;\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						");

						out.print("<p>첨부파일"+"<a href='fileDownload.jsp?fileN="+board.getB_id()+"'>"+board.getB_rfname()+"</a>"+"</p>");
						
      out.write("\r\n");
      out.write("					</td>			\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr height=\"30\" align=\"center\">\r\n");
      out.write("				<td width=\"100\">글제목</td>\r\n");
      out.write("				<td width=\"200\" align=\"left\">\r\n");
      out.write("					");
      out.print( board.getB_title() );
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr height=\"30\" align=\"center\">\r\n");
      out.write("				<td width=\"100\">글내용</td>\r\n");
      out.write("				<td width=\"200\" align=\"left\">\r\n");
      out.write("					");
      out.print( board.getB_content() );
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr height=\"30\">\r\n");
      out.write("				<td colspan=\"4\" align=\"right\">\r\n");
      out.write("					<input type=\"button\" value=\"글수정\" onclick=\"location.href='edit.jsp?b_id=");
      out.print( bid );
      out.write("&pageNum=");
      out.print( pageNum );
      out.write("'\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					<input type=\"button\" value=\"글삭제\" onclick=\"location.href='delete.jsp?b_id=");
      out.print( bid );
      out.write("&pageNum=");
      out.print( pageNum );
      out.write("'\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					<input type=\"button\" value=\"답변글\" onclick=\"location.href='write.jsp?b_id=");
      out.print( bid );
      out.write("&pageNum=");
      out.print( pageNum );
      out.write("'\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("					<input type=\"button\" value=\"글목록\" onclick=\"location.href='list.jsp?pageNum=");
      out.print( pageNum );
      out.write("'\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
